pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - make test
      - make coverage
      - if test ${PYTHON_VERSION} = "3.7-buster"; then make codecov; fi
    secrets: [ codecov_token ]

matrix:
  PYTHON_VERSION:
    - 3.5-jessie
    - 3.6-jessie
    - 3.7-buster
    - 3.8-buster
